# Generated by Django 3.1.5 on 2021-01-18 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_author_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_name',
        ),
    ]
